### ISSUE TITLE
fix quast 5.0.2

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#109]
TravisCI is failing to build the quast 5.0.2 docker image, and I can't get it to build locally. See travis log here https://travis-ci.com/github/StaPH-B/docker-builds/builds/166582909

Seems to be an error during the python install script: `Step 15/16 : RUN cd /quast-5.0.2 &&     /quast-5.0.2/setup.py install`

```
[...]
Installing icarus.py script to /usr/local/bin
Installing quast.py script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/quast-5.0.2-py2.7.egg
Processing dependencies for quast==5.0.2
Searching for simplejson
Reading https://pypi.python.org/simple/simplejson/
Download error on https://pypi.python.org/simple/simplejson/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'simplejson' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for simplejson
error: Could not find suitable distribution for Requirement.parse('simplejson')
```

Then after adding `apt-get install python-simplejson`, I get nearly the same error as TravisCI
```
Installed /usr/local/lib/python2.7/dist-packages/quast-5.0.2-py2.7.egg
Processing dependencies for quast==5.0.2
Searching for joblib
Reading https://pypi.python.org/simple/joblib/
Best match: joblib 0.15.1
Downloading https://files.pythonhosted.org/packages/57/d2/45a038246a0596fb73af64c07e95578764d0fd115ce67f6b41eb457eed39/joblib-0.15.1.tar.gz#sha256=61e49189c84b3c5d99a969d314853f4d1d263316cc694bec17548ebaa9c47b6e
Processing joblib-0.15.1.tar.gz
Writing /tmp/easy_install-261ygp/joblib-0.15.1/setup.cfg
Running joblib-0.15.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-261ygp/joblib-0.15.1/egg-dist-tmp-F56mw2
Traceback (most recent call last):
  File "/quast-5.0.2/setup.py", line 268, in <module>
    script_args=args,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-261ygp/joblib-0.15.1/setup.py", line 6, in <module>
    # All Rights Reserved
  File "/tmp/easy_install-261ygp/joblib-0.15.1/joblib/__init__.py", line 113, in <module>
  File "/tmp/easy_install-261ygp/joblib-0.15.1/joblib/memory.py", line 274
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax
```

I'm stumped on this one.

**Comment by kapsakcj** [comment]
seems like adding `apt-get install python-joblib` fixes it. Will push changes and rebuild on dockerhub soon.

**Comment by kapsakcj** [comment]
this is also an issue with quast 5.0.0 docker image

**Comment by kapsakcj** [comment]
5.0.2 fixed here: https://github.com/StaPH-B/docker-builds/commit/b55a9d4886bf9010a67cfadab18e06fa375f212b

5.0.0 fixed here: https://github.com/StaPH-B/docker-builds/commit/830bd7f497d6256e24023568f2eb4ac00808b9ee

Will rebuild on dockerhub now!
