### ISSUE TITLE
[Bug]: tb-profiler

### ISSUE THREAD

**Issue by karenbobier** [StaPH-B/docker-builds#452]
### What container were you trying to use, and how were you attempting to use it?

I am trying to test the tb-profiler so this is the first time I have run it. Running on an Ubuntu AWS EC2  

code used to run:
```
runfolder="tb_test"

wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR166/009/ERR1664619/ERR1664619_2.fastq.gz

docker run --rm=True -v $PWD:/${runfolder}/ -u $(id -u):$(id -g) staphb/tbprofiler:latest \
tb-profiler profile -1 /$runfolder/ERR1664619_1.fastq.gz -2 /$runfolder/ERR1664619_2.fastq.gz -t 16 -p ERR1664619 --txt 2>tbprofiler_test.err
```
[tbprofiler_test.txt](https://github.com/StaPH-B/docker-builds/files/9538448/tbprofiler_test.txt)

if I add a directory to the command it makes a bit more progress but end with the same permission error
```
tb-profiler profile -1 /$runfolder/ERR1664619_1.fastq.gz -2 /$runfolder/ERR1664619_2.fastq.gz -t 16 -p ERR1664619 --txt --dir /$runfolder/ERR1664619 2>tbprofiler_test.err
```

[tbprofiler_test2.txt](https://github.com/StaPH-B/docker-builds/files/9538513/tbprofiler_test2.txt)

### Relevant log output

```shell
[94mUsing ref file: /opt/conda/share/tbprofiler//tbdb.fasta[0m
[94mUsing gff file: /opt/conda/share/tbprofiler//tbdb.gff[0m
[94mUsing bed file: /opt/conda/share/tbprofiler//tbdb.bed[0m
[94mUsing version file: /opt/conda/share/tbprofiler//tbdb.version.json[0m
[94mUsing json_db file: /opt/conda/share/tbprofiler//tbdb.dr.json[0m
[94mUsing variables file: /opt/conda/share/tbprofiler//tbdb.variables.json[0m
[94mUsing spoligotype_spacers file: /opt/conda/share/tbprofiler//tbdb.spoligotype_spacers.txt[0m
[94mUsing spoligotype_annotations file: /opt/conda/share/tbprofiler//tbdb.spoligotype_list.csv[0m
[94mUsing barcode file: /opt/conda/share/tbprofiler//tbdb.barcode.bed[0m

Running command:
set -u pipefail; trimmomatic PE -threads 16 -phred33 /tb_test/ERR1664619_1.fastq.gz /tb_test/ERR1664619_2.fastq.gz -baseout ./7db16882-32ab-43fd-b6aa-09085bd7ff36 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 619, in <module>
    args.func(args)
  File "/opt/conda/bin/tb-profiler", line 150, in main_profile
    results.update(pp.run_profiler(args))
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 36, in run_profiler
    args.bam_file = get_bam_file(args)
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/cli.py", line 100, in get_bam_file
    fastq_obj = untrimmed_fastq_obj.trim(args.files_prefix,threads=args.threads)
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/fastq.py", line 39, in trim
    run_cmd("trimmomatic PE -threads %(threads)s -phred33 %(r1)s %(r2)s -baseout %(prefix)s LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36" % vars(self))
  File "/opt/conda/lib/python3.9/site-packages/pathogenprofiler/utils.py", line 397, in run_cmd
    raise ValueError("Command Failed:\n%s\nstderr:\n%s" % (cmd,stderr.decode()))
ValueError: Command Failed:
set -u pipefail; trimmomatic PE -threads 16 -phred33 /tb_test/ERR1664619_1.fastq.gz /tb_test/ERR1664619_2.fastq.gz -baseout ./7db16882-32ab-43fd-b6aa-09085bd7ff36 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
stderr:
TrimmomaticPE: Started with arguments:
 -threads 16 -phred33 /tb_test/ERR1664619_1.fastq.gz /tb_test/ERR1664619_2.fastq.gz -baseout ./7db16882-32ab-43fd-b6aa-09085bd7ff36 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
Using templated Output files: ./7db16882-32ab-43fd-b6aa-09085bd7ff36_1P ./7db16882-32ab-43fd-b6aa-09085bd7ff36_1U ./7db16882-32ab-43fd-b6aa-09085bd7ff36_2P ./7db16882-32ab-43fd-b6aa-09085bd7ff36_2U
Exception in thread "main" java.io.FileNotFoundException: ./7db16882-32ab-43fd-b6aa-09085bd7ff36_1P (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.open(FastqSerializer.java:28)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:289)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

Cleaning up after failed run
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 32, in cleanup
    with open(outfile, "w") as O:
PermissionError: [Errno 13] Permission denied: 'ERR1664619.errlog.txt'
```

**Comment by erinyoung** [comment]
This error indicates that it's trying to write to a directory that you don't have permission to write to. The default `workdir` is /data, so this command is trying to write files to /data, but this directory isn't mounted anywhere on your system.

Could you try adding a directory to your `-prefix` option?
```
docker run --rm=True -v $PWD:/${runfolder}/ -u $(id -u):$(id -g) staphb/tbprofiler:latest \
tb-profiler profile -1 /$runfolder/ERR1664619_1.fastq.gz -2 /$runfolder/ERR1664619_2.fastq.gz -t 16 -p /${runfolder}/ERR1664619 --txt 2>tbprofiler_test.err
```

**Comment by kapsakcj** [comment]
I think what is going on here is that trimmomatic is having permission issues with the temporary files that it creates.

I was able to get it to run successfully if I first `cd /tb_test` prior to running tb-profiler. full command:
```
docker run --rm=True -v $PWD:/${runfolder}/ -u $(id -u):$(id -g) staphb/tbprofiler:latest \
    /bin/bash -c "cd /tb_test; tb-profiler profile -1 /$runfolder/ERR1664619_1.fastq.gz -2 /$runfolder/ERR1664619_2.fastq.gz -t 8 -p ERR1664619 --txt --dir /$runfolder/ERR1664619"
```

The default working directory in the container is `/data` and I would recommend using that for reading/writing files to (for permissions reasons)

**Comment by karenbobier** [comment]
thanks @erinyoung and @kapsakcj !

I was able to get it to work both with changing the folder to data and with the extra cd command
