### ISSUE TITLE
[Bug]: KeyError: 'Top Match'

### ISSUE THREAD

**Issue by ybdong919** [StaPH-B/docker-builds#662]
### What container were you trying to use, and how were you attempting to use it?

A bug happened!File "/pmga/pmga", line 1421, in create_json
mash_hit = data[lab_id]["mash_results"]["Top Match"]
KeyError: 'Top Match'

### Relevant log output

```shell
(nextflow) [dongyibo@login1 tmp]$ singularity exec  -B /blue/bphl-florida/dongyibo/Dev_module_Sanibel/Version2/output/JBS22002293:/data docker://staphb/pmga:latest pmga -
-blast /pmga/blastdbs --force /data/JBS22002293_assembly/JBS22002293.fasta
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob c52be5935eb4 done
Copying blob 038dae7ba8b6 done
Copying blob ea362f368469 done
Copying blob f6ea26233069 done
Copying config 00d697b76c done
Writing manifest to image destination
Storing signatures
2023/05/04 10:40:36  info unpack layer: sha256:ea362f368469f909a95f9a6e54ebe0121ce0a8e3c30583dd9c5fb35b14544dec
2023/05/04 10:40:37  info unpack layer: sha256:f6ea262330697dc83fe7ca6d4f23e3fc433f425c107e07cf8ee1dfc0f2ed4e4f
2023/05/04 10:40:42  info unpack layer: sha256:038dae7ba8b643ab1199691768e609e7d60c284f197b2c5ca592a99ac4efb242
2023/05/04 10:40:42  info unpack layer: sha256:c52be5935eb46eea0df9b654f1d95c3c49c82569954b47837ddee03ad1f1733a
INFO:    Creating SIF file...
INFO:    underlay of /etc/localtime required more than 50 (87) bind mounts
Traceback (most recent call last):
  File "/pmga/pmga", line 1640, in <module>
    mash_results = obtain_species(args.fasta, args.threads)
  File "/pmga/pmga", line 1471, in obtain_species
    return create_json(mash_results, thresholds)
  File "/pmga/pmga", line 1421, in create_json
    mash_hit = data[lab_id]["mash_results"]["Top Match"]
KeyError: 'Top Match'
```

**Comment by kapsakcj** [comment]
I don't use `pmga` routinely so I'm not super familiar but it looks like you might have misspelled the input flag `--blastdir`. Can you update this flag and retry the command?

Another option to test is that you could try using a biocontainer docker image instead of the staphb docker image: https://quay.io/repository/biocontainers/pmga?tab=tags

**Comment by ybdong919** [comment]
Even I use --blast, the same thing happened.

**Comment by ybdong919** [comment]
For the container in biocontainer, the same error appeared.
So I think the input file can not be correctly handled by the script. 
Do you know any special rules for the fasta file?

**Comment by kapsakcj** [comment]
@rpetit3 any ideas? ever seen this error before with pmga?

@ybdong919 If you are able to share the FASTA file here (or privately), I can attempt to reproduce the error

**Comment by ybdong919** [comment]
>lcl|NZ_CP021520.1_cds_WP_002223060.1_1 [gene=dnaA] [locus_tag=CCD84_RS00010] [db_xref=GeneID:61280603] [protein=chromosomal replication initiator protein DnaA] [protein_id=WP_002223060.1] [location=1..1557] [gbkey=CDS]
ATGACATTAGCAGAGTTTTGGCCGCTGTGCCTCCGCCGTCTTCACGATATGTTGCCTCAAGGGCAGTTTG
CGCAATGGATTGCGCCCCTTACCGTTGGTGAGGAGGGTGGCGTATGGGTGGTGTACGGCAAGAACCAGTT
TGCCTGCAATATGCTCAAGAGCCAGTTTGCCGGAAAAATAGAAGCGGTGAGGGAAGAGTTGGCTGCCGGC
CGTTCCGCCTTCGTATTCAAACCGGGAGAAGGCGTGCGTTATGAGATGGCGGCGGTTGAAGGTGCTGTCG
AACCTGCCGAGCCGTCCTTGCATGCGGTGTCGGAGGGAATGCCCGTGCAGGAGGTTCTGTTGGACGAGCT
GCCGTCTGAAGAGCCTGTCAAACCCGCTGCGTCGAAAACGGCGGCGGATATTTTGGCGGAACGTATGAAA
AACCTGCCGCACGAGCCGCGTCAGGCTGCCGGGTCTGCTTCCCGGCCGGAATCGGTGGCAGTTGCCAAAG
CACGGACGGACGTGCAGCGCGATGCGGAAGAGGCGCGTTACGAGCAGACCAACCTGTCTCCGGATTACAC
GTTTGATACGTTGGTAGAAGGTAAGGGCAACCGCCTTGCGGCGGCTGCGGCGCAGGCGATTGCGGAAAGC
CCGGGGCAGAGTTACAACCCGTTCTTCCTCTATGGCAGTACGGGTTTGGGCAAAACCCACCTTGTGCAGG
CGGTCGGCAACGAGCTGCTGAAAAACCGTCCCGATGCCAAAGTGCGCTATATGCATTCGGATGACTATAT
CCGCAGCTTTATGAAGGCGGTTCGCAACAACACTTACGACGTGTTCAAGCAGCAATACAAGCAATACGAC
CTGCTGATTATCGACGACATCCAGTTCATCAAAGGCAAAGACCGTACGATGGAAGAGTTTTTCTATCTGT
ACAACCATTTCCACAACGAGAAAAAACAGCTCATCCTCACTTGCGATGTGTTGCCTGCGAAAATCGAAGG
CATGGACGACCGCCTCAAATCCCGTTTTTCATGGGGACTGACTTTGGAACTCGAGCCGCCCGAATTGGAA
ATGCGCATCGCCATTTTGCAGAAAAAGGCGGAAGCGGCGGGCATCAGTATCGAAGACGAAGCCGCGCTGT
TCATTGCCAATCTGATCCGTTCCAACGTGCGCGAGCTTGAAGGCGCGTTTAATCGTGTCGGAGCGAGCAG
CCGCTTTATGAACCGTCCCGTCATCGACATCGATTTGGCGCGTACCGCTTTGCAGGACATTATTGCCGAG
AAGCACAAAGTCATCACCGCCGACATCATCATCGATGCGGTGGCGAAATATTACCGCATCAAAATCAGCG
ATGTGCTCGGTAAGAAACGGACACGAAACATTGCCCGTCCGCGCCAGGTGGCGATGAGCCTGACCAAAGA
ACTGACTACTTTGAGCCTGCCGTCTATCGGCGATTCGTTTGGTGGGCGCGACCATACGACCGTTATGCAC
GGCATCAGGGCAGTGGCGAAACTGCGCGAAGAAGATCCGGAATTGGCTCAGGATTATGAAAAGCTGCTGA
TTCTGATTCAAAACTGA

**Comment by ybdong919** [comment]
>>lcl|NZ_CP021520.1_cds_WP_002223060.1_1 [gene=dnaA] [locus_tag=CCD84_RS00010] [db_xref=GeneID:61280603] [protein=chromosomal replication initiator protein DnaA] [protein_id=WP_002223060.1] [location=1..1557] [gbkey=CDS]
ATGACATTAGCAGAGTTTTGGCCGCTGTGCCTCCGCCGTCTTCACGATATGTTGCCTCAAGGGCAGTTTG
CGCAATGGATTGCGCCCCTTACCGTTGGTGAGGAGGGTGGCGTATGGGTGGTGTACGGCAAGAACCAGTT
TGCCTGCAATATGCTCAAGAGCCAGTTTGCCGGAAAAATAGAAGCGGTGAGGGAAGAGTTGGCTGCCGGC
CGTTCCGCCTTCGTATTCAAACCGGGAGAAGGCGTGCGTTATGAGATGGCGGCGGTTGAAGGTGCTGTCG
AACCTGCCGAGCCGTCCTTGCATGCGGTGTCGGAGGGAATGCCCGTGCAGGAGGTTCTGTTGGACGAGCT
GCCGTCTGAAGAGCCTGTCAAACCCGCTGCGTCGAAAACGGCGGCGGATATTTTGGCGGAACGTATGAAA
AACCTGCCGCACGAGCCGCGTCAGGCTGCCGGGTCTGCTTCCCGGCCGGAATCGGTGGCAGTTGCCAAAG
CACGGACGGACGTGCAGCGCGATGCGGAAGAGGCGCGTTACGAGCAGACCAACCTGTCTCCGGATTACAC
GTTTGATACGTTGGTAGAAGGTAAGGGCAACCGCCTTGCGGCGGCTGCGGCGCAGGCGATTGCGGAAAGC
CCGGGGCAGAGTTACAACCCGTTCTTCCTCTATGGCAGTACGGGTTTGGGCAAAACCCACCTTGTGCAGG
CGGTCGGCAACGAGCTGCTGAAAAACCGTCCCGATGCCAAAGTGCGCTATATGCATTCGGATGACTATAT
CCGCAGCTTTATGAAGGCGGTTCGCAACAACACTTACGACGTGTTCAAGCAGCAATACAAGCAATACGAC
CTGCTGATTATCGACGACATCCAGTTCATCAAAGGCAAAGACCGTACGATGGAAGAGTTTTTCTATCTGT
ACAACCATTTCCACAACGAGAAAAAACAGCTCATCCTCACTTGCGATGTGTTGCCTGCGAAAATCGAAGG
CATGGACGACCGCCTCAAATCCCGTTTTTCATGGGGACTGACTTTGGAACTCGAGCCGCCCGAATTGGAA
ATGCGCATCGCCATTTTGCAGAAAAAGGCGGAAGCGGCGGGCATCAGTATCGAAGACGAAGCCGCGCTGT
TCATTGCCAATCTGATCCGTTCCAACGTGCGCGAGCTTGAAGGCGCGTTTAATCGTGTCGGAGCGAGCAG
CCGCTTTATGAACCGTCCCGTCATCGACATCGATTTGGCGCGTACCGCTTTGCAGGACATTATTGCCGAG
AAGCACAAAGTCATCACCGCCGACATCATCATCGATGCGGTGGCGAAATATTACCGCATCAAAATCAGCG
ATGTGCTCGGTAAGAAACGGACACGAAACATTGCCCGTCCGCGCCAGGTGGCGATGAGCCTGACCAAAGA
ACTGACTACTTTGAGCCTGCCGTCTATCGGCGATTCGTTTGGTGGGCGCGACCATACGACCGTTATGCAC
GGCATCAGGGCAGTGGCGAAACTGCGCGAAGAAGATCCGGAATTGGCTCAGGATTATGAAAAGCTGCTGA
TTCTGATTCAAAACTGA

**Comment by ybdong919** [comment]
>lcl|NZ_CP021520.1_cds_WP_002223060.1_1 [gene=dnaA] [locus_tag=CCD84_RS00010] [db_xref=GeneID:61280603] [protein=chromosomal replication initiator protein DnaA] [protein_id=WP_002223060.1] [location=1..1557] [gbkey=CDS]
ATGACATTAGCAGAGTTTTGGCCGCTGTGCCTCCGCCGTCTTCACGATATGTTGCCTCAAGGGCAGTTTG
CGCAATGGATTGCGCCCCTTACCGTTGGTGAGGAGGGTGGCGTATGGGTGGTGTACGGCAAGAACCAGTT
TGCCTGCAATATGCTCAAGAGCCAGTTTGCCGGAAAAATAGAAGCGGTGAGGGAAGAGTTGGCTGCCGGC
CGTTCCGCCTTCGTATTCAAACCGGGAGAAGGCGTGCGTTATGAGATGGCGGCGGTTGAAGGTGCTGTCG
AACCTGCCGAGCCGTCCTTGCATGCGGTGTCGGAGGGAATGCCCGTGCAGGAGGTTCTGTTGGACGAGCT
GCCGTCTGAAGAGCCTGTCAAACCCGCTGCGTCGAAAACGGCGGCGGATATTTTGGCGGAACGTATGAAA
AACCTGCCGCACGAGCCGCGTCAGGCTGCCGGGTCTGCTTCCCGGCCGGAATCGGTGGCAGTTGCCAAAG
CACGGACGGACGTGCAGCGCGATGCGGAAGAGGCGCGTTACGAGCAGACCAACCTGTCTCCGGATTACAC
GTTTGATACGTTGGTAGAAGGTAAGGGCAACCGCCTTGCGGCGGCTGCGGCGCAGGCGATTGCGGAAAGC
CCGGGGCAGAGTTACAACCCGTTCTTCCTCTATGGCAGTACGGGTTTGGGCAAAACCCACCTTGTGCAGG
CGGTCGGCAACGAGCTGCTGAAAAACCGTCCCGATGCCAAAGTGCGCTATATGCATTCGGATGACTATAT
CCGCAGCTTTATGAAGGCGGTTCGCAACAACACTTACGACGTGTTCAAGCAGCAATACAAGCAATACGAC
CTGCTGATTATCGACGACATCCAGTTCATCAAAGGCAAAGACCGTACGATGGAAGAGTTTTTCTATCTGT
ACAACCATTTCCACAACGAGAAAAAACAGCTCATCCTCACTTGCGATGTGTTGCCTGCGAAAATCGAAGG
CATGGACGACCGCCTCAAATCCCGTTTTTCATGGGGACTGACTTTGGAACTCGAGCCGCCCGAATTGGAA
ATGCGCATCGCCATTTTGCAGAAAAAGGCGGAAGCGGCGGGCATCAGTATCGAAGACGAAGCCGCGCTGT
TCATTGCCAATCTGATCCGTTCCAACGTGCGCGAGCTTGAAGGCGCGTTTAATCGTGTCGGAGCGAGCAG
CCGCTTTATGAACCGTCCCGTCATCGACATCGATTTGGCGCGTACCGCTTTGCAGGACATTATTGCCGAG
AAGCACAAAGTCATCACCGCCGACATCATCATCGATGCGGTGGCGAAATATTACCGCATCAAAATCAGCG
ATGTGCTCGGTAAGAAACGGACACGAAACATTGCCCGTCCGCGCCAGGTGGCGATGAGCCTGACCAAAGA
ACTGACTACTTTGAGCCTGCCGTCTATCGGCGATTCGTTTGGTGGGCGCGACCATACGACCGTTATGCAC
GGCATCAGGGCAGTGGCGAAACTGCGCGAAGAAGATCCGGAATTGGCTCAGGATTATGAAAAGCTGCTGA
TTCTGATTCAAAACTGA

**Comment by kapsakcj** [comment]
Looks like something is going on with the `mash` step within `pmga`. Likely because you are not providing a full genome assembly, but rather a single gene (I think?)

if you provide the `--species neisseria` (or `--species hinfluenzae`) flag, it will skip mash and go right to running blast. I was able to get past that error with your FASTA file:

```bash
$ pmga --blastdir /pmga/blastdbs/ fl-pmga.fasta --force --species hinfluenzae -t 8
2023-05-04 19:40:22:root:INFO - Found --force, removing existing /data/pmga
2023-05-04 19:40:22:root:INFO - Using species: {species}
2023-05-04 19:40:22:root:INFO - Step 1. BLASTing against PubMLST DBs
2023-05-04 19:40:22:root:INFO - Blasting against pubMLST database with 8 workers for file fl-pmga.fasta
2023-05-04 19:40:38:root:INFO - Completed BLAST for fl-pmga.fasta
2023-05-04 19:40:38:root:INFO - Evaluating BLAST Results
2023-05-04 19:40:38:root:INFO - Step 2. Parsing BLAST results
2023-05-04 19:40:38:root:INFO - Parsing BLAST data to identify alleles to extract from pubMLST
2023-05-04 19:40:38:root:INFO - Compiling results
2023-05-04 19:40:38:root:INFO - Step 3. Writing outputs
```

**Comment by ybdong919** [comment]
Thanks a lot. It works for me. 
One more question:
Is there a flag to input mash distance file in pmga command line if I already have mash output files before running pmga?

**Comment by ybdong919** [comment]
Really appreciate your great help!
