### ISSUE TITLE
Requesting an update to medaka containers to include r10 models

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#689]
### What container needs an update?

I know all of these containers are awesome, but I'm not currently seeing a medaka container with r10 models available.

**Comment by erinyoung** [comment]
I think this is another issue related to https://github.com/StaPH-B/docker-builds/issues/204 . I think I will close that one in lieu of this new request so that we can keep the conversation going.

In summary, the medaka containers were too large for me to download and test, so I have been using ONT containers.

**Comment by kevinlibuit** [comment]
Ah, I take back my original comment: it does appear a few r10 models are available in the `quay.io/staphb/artic-ncov2019-epi2me` container, but no r10.4 models.

Still the same sentiment: will be worth updating things accordingly as PHL are upgrading flow cells. Even seeing adoption of Dorado; no dorado-specific model available yet, but saw an [ont recommendation](https://github.com/nanoporetech/medaka/issues/405#issuecomment-1386763081) to use guppy models not available in these images.

**Comment by erinyoung** [comment]
For my future notes, this is what the error looks like when running artic with a model that isn't there:

```
Command error:
  [M::mm_idx_stat::0.008*1.35] distinct minimizers: 5[587](https://github.com/UPHL-BioNGS/Cecret/actions/runs/6043198519/job/16399778645?pr=221#step:5:588) (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332; total length: 29903
  [M::worker_pipeline::3.075*1.48] mapped 20706 sequences
  [M::main] Version: 2.24-r1122
  [M::main] CMD: minimap2 -a -x map-ont -t 2 schema/cecret/V1/cecret.reference.fasta SRR22452250_1_filtered.fastq.gz
  [M::main] Real time: 3.076 sec; CPU: 4.563 sec; Peak RSS: 0.039 GB
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/medaka/medaka.py", line 35, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/usr/local/lib/python3.8/site-packages/medaka/models.py", line 87, in resolve_model
      raise RuntimeError(
  RuntimeError: The model file for r941_min_high_g360 is not installed and could not be installed to any of /usr/local/lib/python3.8/site-packages/medaka/data or /.medaka/data. If you cannot gain write permissions, download the model file manually from https://github.com/nanoporetech/medaka/raw/master/medaka/data/r941_min_high_g360_model.hdf5 and use the downloaded model as the --model option.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.8/site-packages/medaka/medaka.py", line 699, in main
      args = parser.parse_args()
    File "/usr/local/lib/python3.8/argparse.py", line 1768, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/usr/local/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/usr/local/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/usr/local/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/usr/local/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/usr/local/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/usr/local/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/usr/local/lib/python3.8/argparse.py", line 2006, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/usr/local/lib/python3.8/argparse.py", line 1946, in consume_optional
      take_action(action, args, option_string)
    File "/usr/local/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/usr/local/lib/python3.8/site-packages/medaka/medaka.py", line 38, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: The model file for r941_min_high_g360 is not installed and could not be installed to any of /usr/local/lib/python3.8/site-packages/medaka/data or /.medaka/data. If you cannot gain write permissions, download the model file manually from https://github.com/nanoporetech/medaka/raw/master/medaka/data/r941_min_high_g360_model.hdf5 and use the downloaded model as the --model option..
  Running: minimap2 -a -x map-ont -t 2 schema/cecret/V1/cecret.reference.fasta SRR22452250_1_filtered.fastq.gz | samtools view -bS -F 4 - | samtools sort -o artic/SRR22452250_1.sorted.bam -
  Running: samtools index artic/SRR22452250_1.sorted.bam
  Running: align_trim --normalise 200 schema/cecret/V1/cecret.scheme.bed --start --remove-incorrect-pairs --report artic/SRR22452250_1.alignreport.txt < artic/SRR22452250_1.sorted.bam 2> artic/SRR22452250_1.alignreport.er | samtools sort -T artic/SRR22452250_1 - -o artic/SRR22452250_1.trimmed.rg.sorted.bam
  Running: align_trim --normalise 200 schema/cecret/V1/cecret.scheme.bed --remove-incorrect-pairs --report artic/SRR22452250_1.alignreport.txt < artic/SRR22452250_1.sorted.bam 2> artic/SRR22452250_1.alignreport.er | samtools sort -T artic/SRR22452250_1 - -o artic/SRR22452250_1.primertrimmed.rg.sorted.bam
  Running: samtools index artic/SRR22452250_1.trimmed.rg.sorted.bam
  Running: samtools index artic/SRR22452250_1.primertrimmed.rg.sorted.bam
  Running: medaka consensus --model r941_min_high_g360 --threads 2 --chunk_len 800 --chunk_ovlp 400 --RG 1 artic/SRR22452250_1.trimmed.rg.sorted.bam artic/SRR22452250_1.1.hdf
  Command failed:medaka consensus --model r941_min_high_g360 --threads 2 --chunk_len 800 --chunk_ovlp 400 --RG 1 artic/SRR22452250_1.trimmed.rg.sorted.bam artic/SRR22452250_1.1.hdf
  ```

**Comment by erinyoung** [comment]
Right now, the artic-ncov2019-epi2me is a bit out of date. There is currently version 0.3.31 available. 

The prior Dockerfile for artic-ncov2019-epi2me is missing the app and test layer as well as the CMD line, but has most of the template included.
