### ISSUE TITLE
nanoplot missing python dependency

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#84]
Got this error when running the NanoPlot 1.27.0 container:
```
2020-03-17 16:37:51,632 Nanoplotter: orca not found, not creating static image of html. See https://github.com/plotly/orca
2020-03-17 16:37:51,633 Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nanoplotter/plot.py", line 60, in save_static
    pio.write_image(self.fig, self.path.replace('html', 'png'))
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1705, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1482, in to_image
    ensure_server()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1325, in ensure_server
    """
ValueError: Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil
```

I'll update the 1.27.0 image and make a new image for the latest version available on pypi `NanoPlot 1.29.0` https://pypi.org/project/NanoPlot/

**Comment by kapsakcj** [comment]
Fixed the psutil error, now getting an error about `orca`
```
2020-03-17 17:10:51,788 Nanoplotter: orca not found, not creating static image of html. See https://github.com/plotly/orca
2020-03-17 17:10:51,788
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()
```

**Comment by kapsakcj** [comment]
grrrrrrrrrrr installing `orca` is not straightforward......blehl;jkasdflk;jsadfl;kjsadf

**Comment by kapsakcj** [comment]
orca is optional 👍 Will fix and make a dockerfile for the latest release of NanoPlot

https://github.com/wdecoster/NanoPlot/issues/174

**Comment by kapsakcj** [comment]
Done in https://github.com/StaPH-B/docker-builds/commit/572f86056aec3b56130c9646f9e141fc03376b88 and https://github.com/StaPH-B/docker-builds/commit/eba80f2235b8ab2b595d7a2089ba6ca3265241a4
